name: Prevent-triggers
on: 
  push:
    branches: 
      - 'master'
    paths:
      - .github/workflows/prevent.yml

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Stage
        run: echo "This is Build stage"

  Test:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Test Stage
        run: echo "This is test stage"

  Deploy:
    needs: Test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Stage
        run: echo "This is Deploy stage"

  Notify:
    needs: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Notify Stage
        run: echo "This is notify stage"
