name: Use Variable Example

on: 
  push:
    branches:
      - master
env : 
  MY_VARIABLE : Guna
  rollback : true
  rollback_version: 1.1.4

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Use GitHub variable
        run: echo $MY_VARIABLE
        run: echo $rollback
        run : echo $rollback_version
